name: Build, Pack, and Store Artifacts
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
    contents: write
jobs:
    init:
        uses: ./.github/workflows/reusable-uipath-cli-initialization.yml
        with:
            environment: Development
            runs-on: ubuntu-latest

    build-pack-store:
        needs: init
        environment: ${{ needs.init.outputs.environment }}
        runs-on: ${{ needs.init.outputs.runs-on }}
        steps:
        -   name: Check out repository
            uses: actions/checkout@v4

        -   name: Create Version Tag
            id: create-tag
            run: node ${{ needs.init.outputs.dir-scripts }}/create-release-tag.ts
            
        -   name: Generate Deployment Configurations
            run: |
                node ${{ needs.init.outputs.dir-scripts }}/generate-deployment-configurations.ts \
                    --config-dir ${{ needs.init.outputs.dir-configs }} \
                    --output-dir ${{ needs.init.outputs.dir-generated }} \
                    --global-config ${{ needs.init.outputs.dir-deployment }}/global.deploy.json
            
        -   name: Build the Project
            run: uip rpa build ${{ needs.init.outputs.dir-rpa-simulacrum }} 

        -   name: Pack the Project
            run: |
                node ${{ needs.init.outputs.dir-scripts }}/create-nuget-packages.ts \
                    --config-dir ${{ needs.init.outputs.dir-generated }} \
                    --project-dir ${{ needs.init.outputs.dir-rpa-simulacrum }} \
                    --release-version ${{ env.RELEASE_TAG }}

        -   name: Store Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: rpa-artifacts-${{ env.RELEASE_TAG }}
                path: ${{ needs.init.outputs.dir-distribution }}/**
