name: Build, Pack, and Store Artifacts
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
    contents: read

concurrency:
    group: build-pack-store-${{ github.ref }}
    cancel-in-progress: false

jobs:
    init:
        if: ${{ github.event_name != 'pull_request' }}
        uses: ./.github/workflows/reusable-variables.yml
        with:
            environment: Development

    build-pack-store:
        if: ${{ github.event_name != 'pull_request' }}
        needs: init
        permissions:
            contents: write
        environment: ${{ needs.init.outputs.environment }}
        runs-on: ${{ needs.init.outputs.runs-on }}
        steps:
        -   name: Log Variables
            run: |
                echo "Environment: ${{ needs.init.outputs.environment }}"
                echo "Runs-on: ${{ needs.init.outputs.runs-on }}"
                echo "Directories:"
                echo "Deployment: ${{ needs.init.outputs.dir-deployment }}"
                echo "Scripts: ${{ needs.init.outputs.dir-scripts }}"
                echo "Configs: ${{ needs.init.outputs.dir-configs }}"
                echo "Generated: ${{ needs.init.outputs.dir-generated }}"
                echo "Distribution: ${{ needs.init.outputs.dir-distribution }}"
                echo "RPA Simulacrum: ${{ needs.init.outputs.dir-rpa-simulacrum }}"

        -   name: Check out repository
            uses: actions/checkout@v7

        -   name: Initialize UiPath CLI Environment
            uses: ./.github/actions/initialize-uipath-cli

        -   name: UiPath Login
            env:
                UIPATH_AUTHORITY: ${{ vars.UIPATH_AUTHORITY }}
                UIPATH_ORGANIZATION: ${{ vars.UIPATH_ORGANIZATION }}
                UIPATH_TENANT_NAME: ${{ vars.UIPATH_TENANT_NAME }}
                UIPATH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
                UIPATH_SECRET: ${{ secrets.UIPATH_SECRET }}
            run: |
                echo "Logging into UiPath Orchestrator..."
                uip login \
                    --authority "$UIPATH_AUTHORITY" \
                    --organization "$UIPATH_ORGANIZATION" \
                    --tenant "$UIPATH_TENANT_NAME" \
                    --client-id env.UIPATH_CLIENT_ID \
                    --client-secret env.UIPATH_SECRET \
                    --output json

        -   name: Build the Project
            run: |
                uip rpa build "${{ needs.init.outputs.dir-rpa-simulacrum }}" \
                --log-level Warn \
                --output json 

        -   name: Generate Release Version
            run: node ${{ needs.init.outputs.dir-scripts }}/create-release-tag.ts
            
        -   name: Generate Deployment Configurations
            run: |
                node ${{ needs.init.outputs.dir-scripts }}/generate-deployment-configurations.ts \
                    --config-dir ${{ needs.init.outputs.dir-configs }} \
                    --output-dir ${{ needs.init.outputs.dir-generated }} \
                    --global-config ${{ needs.init.outputs.dir-deployment }}/global.deploy.json

        -   name: Pack the Project
            run: |
                node ${{ needs.init.outputs.dir-scripts }}/create-nuget-packages.ts \
                    --config-dir ${{ needs.init.outputs.dir-generated }} \
                    --project-dir ${{ needs.init.outputs.dir-rpa-simulacrum }} \
                    --release-version ${{ env.RELEASE_TAG }}

        -   name: Store Artifacts
            id: store-artifacts
            env:
                RELEASE_TAG: ${{ env.RELEASE_TAG }}
            uses: actions/upload-artifact@v7
            with:
                name: rpa-artifacts-${{ env.RELEASE_TAG }}
                path: dist/${{ env.RELEASE_TAG }}/**
                if-no-files-found: error

        -   name: Create Release Metadata
            env:
                TAG: ${{ env.RELEASE_TAG }}
                ID: ${{ steps.store-artifacts.outputs.artifact-id }}
                URL: ${{ steps.store-artifacts.outputs.artifact-url }}
                DIGEST: ${{ steps.store-artifacts.outputs.artifact-digest }}
            run: |
                node ${{ needs.init.outputs.dir-scripts }}/create-deployment-metadata.ts \
                    --tag $TAG \
                    --id $ID \
                    --url $URL \
                    --digest $DIGEST \
                    --outfile ${{ needs.init.outputs.release-metadata }}
        -   name: Push Release Tag
            run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git commit -m "Add release metadata for ${{ env.RELEASE_TAG }}" ${{ needs.init.outputs.release-metadata }}
                git tag ${{ env.RELEASE_TAG }}"
                git push origin ${{ env.RELEASE_TAG }}"
        