name: Publish Artifacts to Orchestrator (Development)

on:
  workflow_dispatch:  
    inputs:
        release-tag:
            description: 'Release tag for the artifacts to publish'
            required: true
            type: string

jobs:
    publish-to-development:
        uses: ./.github/workflows/publish-rpa-workflow.yml
        with:
            environment: 'Development'
            runs-on: 'ubuntu-latest'
            release-tag: ${{ inputs.release-tag }}
       