name: Publish Artifacts to Orchestrator

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use for publishing artifacts'
        required: true
        default: 'Development'
        type: environment
      release-tag:
        description: 'Release tag for the artifacts to publish'
        required: true
        type: string

permissions:
    actions: read
    contents: read

jobs:
    init:
        uses: ./.github/workflows/reusable-variables.yml
        with:
            environment: ${{ inputs.environment }}

    publish-packages:
        needs: init
        runs-on: ${{ needs.init.outputs.runs-on }}
        environment: ${{ inputs.environment }}
        steps:
        -   name: Checkout Repository
            uses: actions/checkout@v4
            with:
                ref: '${{ inputs.release-tag }}'

        -   name: Read Release Metadata
            id: metadata
            uses: ActionsTools/read-json-action@main
            with:
                file_path: ${{ needs.init.outputs.release-metadata }}
        -   run: |
                echo "version:${{ steps.metadata.outputs.version}}" 
                echo "artifact-id: ${{ steps.metadata.outputs.artifact-id}}" 
                echo "artifact-url: ${{ steps.metadata.outputs.artifact-url}}" 
                echo "artifact-digest: ${{ steps.metadata.outputs.artifact-digest}}"

        -   name: Download Release Artifacts
            uses: actions/download-artifact@v8
            with:
                name: rpa-artifacts-2026.08.02.050119
#                name: rpa-artifacts-${{ steps.metadata.outputs.version }}
                path: ${{ needs.init.outputs.dir-distribution }}
        
        -   name: List Artifacts
            run: ls -R ${{ needs.init.outputs.dir-distribution }}