name: Buildscript Variable Initialization
on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            runs-on:
                type: string
                default: ubuntu-latest
        
        outputs: 
            environment:
                value: ${{ jobs.environment-variables.outputs.environment }}
            runs-on:
                value: ${{ jobs.environment-variables.outputs.runs-on }}
            dir-deployment:
                value: ${{ jobs.environment-variables.outputs.dir-deployment }}
            dir-scripts:
                value: ${{ jobs.environment-variables.outputs.dir-scripts }}
            dir-configs:
                value: ${{ jobs.environment-variables.outputs.dir-configs }}
            dir-generated:
                value: ${{ jobs.environment-variables.outputs.dir-generated }}
            dir-distribution:
                value: ${{ jobs.environment-variables.outputs.dir-distribution }}
            dir-rpa-simulacrum:
                value: ${{ jobs.environment-variables.outputs.dir-rpa-simulacrum }}
            release-metadata:
                value: ${{ jobs.environment-variables.outputs.release-metadata }}

jobs:
    environment-variables:
        runs-on: ${{ inputs.runs-on }}
        environment: ${{ inputs.environment }}
        outputs:
            runs-on: ${{ inputs.runs-on }}
            environment: ${{ inputs.environment }}
            release-metadata: ${{ steps.paths.outputs.release-metadata }}
            dir-deployment: ${{ steps.paths.outputs.dir-deployment }}
            dir-scripts: ${{ steps.paths.outputs.dir-scripts }}
            dir-configs: ${{ steps.paths.outputs.dir-configs }}
            dir-generated: ${{ steps.paths.outputs.dir-generated }}
            dir-distribution: ${{ steps.paths.outputs.dir-distribution }}
            dir-rpa-simulacrum: ${{ steps.paths.outputs.dir-rpa-simulacrum }}

        steps:
        -   name: Define directory paths
            id: paths
            shell: bash
            run: |
                echo "dir-deployment=.github/deployment" >> "$GITHUB_OUTPUT"
                echo "dir-scripts=.github/scripts" >> "$GITHUB_OUTPUT"
                echo "dir-configs=.github/deployment/configs" >> "$GITHUB_OUTPUT"
                echo "dir-generated=.github/deployment/generated-configs" >> "$GITHUB_OUTPUT"
                echo "dir-distribution=artifact-distribution" >> "$GITHUB_OUTPUT"
                echo "dir-rpa-simulacrum=rpa-workflows/Simulacrum" >> "$GITHUB_OUTPUT"
                echo "release-metadata=.github/deployment/release-metadata.json" >> "$GITHUB_OUTPUT"



    
