name: UiPath CLI Environment Initialization
on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            runs-on:
                type: string
                default: ubuntu-latest
        
        outputs: 
            environment:
                value: ${{ inputs.environment }}
            runs-on:
                value: ${{ jobs.environment-variables.outputs.runs-on }}
            dir-deployment:
                value: ${{ jobs.environment-variables.outputs.dir-deployment }}
            dir-scripts:
                value: ${{ jobs.environment-variables.outputs.dir-scripts }}
            dir-configs:
                value: ${{ jobs.environment-variables.outputs.dir-configs }}
            dir-generated:
                value: ${{ jobs.environment-variables.outputs.dir-generated }}
            dir-distribution:
                value: ${{ jobs.environment-variables.outputs.dir-distribution }}
            dir-rpa-simulacrum:
                value: ${{ jobs.environment-variables.outputs.dir-rpa-simulacrum }}

jobs:
    environment-variables:
        runs-on: ${{ inputs.runs-on }}
        environment: ${{ inputs.environment }}
        outputs:
            runs-on: ${{ inputs.runs-on }}
            dir-deployment: ${{ steps.paths.outputs.dir-deployment }}
            dir-scripts: ${{ steps.paths.outputs.dir-scripts }}
            dir-configs: ${{ steps.paths.outputs.dir-configs }}
            dir-generated: ${{ steps.paths.outputs.dir-generated }}
            dir-distribution: ${{ steps.paths.outputs.dir-distribution }}
            dir-rpa-simulacrum: ${{ steps.paths.outputs.dir-rpa-simulacrum }}

        steps:
        -   name: Define directory outputs
            id: paths
            shell: bash
            run: |
                echo "dir-deployment=.github/deployment" >> "$GITHUB_OUTPUT"
                echo "dir-scripts=.github/scripts" >> "$GITHUB_OUTPUT"
                echo "dir-configs=.github/deployment/configs" >> "$GITHUB_OUTPUT"
                echo "dir-generated=.github/deployment/generated-configs" >> "$GITHUB_OUTPUT"
                echo "dir-distribution=artifact-distribution" >> "$GITHUB_OUTPUT"
                echo "dir-rpa-simulacrum=rpa-workflows/Simulacrum" >> "$GITHUB_OUTPUT"

    directories:
        needs: environment-variables
        runs-on: ${{ inputs.runs-on }}
        environment: ${{ inputs.environment }}
        steps:
        -   name: Create distribution directory
            env:
                DIR_DISTRIBUTION: >-
                    ${{ needs.environment-variables.outputs.dir-distribution }}
            run: |
                echo "Directory: $DIR_DISTRIBUTION"
                mkdir -p "$DIR_DISTRIBUTION"

    uipath-cli:
        needs: environment-variables
        runs-on: ${{ inputs.runs-on }}
        environment: ${{ inputs.environment }}
        steps:        
        -   name: Set up Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 'latest' # You can also use 'current' or '*'
                check-latest: true     
        -   name: Verify Node.js Version
            run: node -v    

        -   name: Install UiPath CLI
            run: npm install -g @uipath/cli
            
        -   name: Pre-Install UiPath CLI Tools
            run: |
                uip tools install @uipath/orchestrator-tool
                uip tools install @uipath/rpa-tool



    
